# Each Docker image must have the same name as its corresponding service.
# The Dockerfiles must be called in your docker-compose.yml by your Makefile.
# build the Docker images using docker-compose.yml
# Of course, using network: host or --link or links: is forbidden.
# The network line must be present in your docker-compose.yml file.

# version: '3.7'

services:
  mariadb:
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    env_file: .env
    environment:
      # MariaDB looks for specific environment variable names.
      MYSQL_PASSWORD_FILE: /run/secrets/db_pass
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_pass
    volumes:
      - mariadbVol:/var/lib/mysql
    networks:
      - inception-network
    secrets:
      - db_pass
      - db_root_pass
    expose:
      - "3306"
    restart: always

  wordpress:
    image: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    env_file: .env
    environment:
      DB_PASS_FILE: /run/secrets/db_pass
    volumes:
      - wordpressVol:/var/www/html
    networks:
      - inception-network
    secrets:
      - db_pass
      - wp_admin_pass
      - wp_user_pass
    expose:
      - "9000"
    restart: always
    depends_on:
      - mariadb

  nginx:
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpressVol:/var/www/html
    networks:
      - inception-network
    restart: always
    depends_on:
      - wordpress

networks:
  inception-network:
    driver: bridge
    name: inception-network

volumes:
  mariadbVol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/akdemir/data/mariadb
  wordpressVol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/akdemir/data/wordpress

secrets:
  db_pass:
    file: ./secrets/db_pass
  db_root_pass:
    file: ./secrets/db_root_pass
  wp_user_pass:
    file: ./secrets/wp_user_pass
  wp_admin_pass:
    file: ./secrets/wp_admin_pass
